language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
services:
  - xvfb
env:
  - "TARGET=test_repl_builtin"
  - "TARGET=test_repl_ipython"
  - "TARGET=test_repl_idle"
  - "TARGET=test"
  - "TARGET=test_fmt"
  - "TARGET=test_asm"
jobs:
  exclude:
    - python: "3.5"
      env: "TARGET=test_asm"
install:
  - bash .travis.install
script:
  - make ${TARGET}
cache:
  directories:
    - /home/travis/.cache/
